name: Sync ReadMe

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Check conflicts with documentation
        uses: readmeio/rdme@7.5.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=1.0 --dryRun

      - name: Sync documentation to ReadMe
        if: github.event.ref == 'refs/heads/main'
        uses: readmeio/rdme@7.5.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=1.0

  openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update OpenAPI JSON
        run: python generate_openapi.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📝 Update OpenAPI definition"

      - name: Validate OpenAPI JSON
        uses: readmeio/rdme@7.5.0
        with:
          rdme: validate openapi.json

      - name: Sync OpenAPI JSON to ReadMe
        if: github.ref == 'refs/heads/main'
        uses: readmeio/rdme@7.5.0
        with:
          rdme: openapi openapi.json --key=${{ secrets.README_API_KEY }} --id=62ff2ebb60122600a129088c
