name: Sync documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Check conflicts with documentation
        uses: readmeio/rdme@7.5.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=1.0 --dryRun

      - name: Sync documentation to ReadMe
        if: github.event.ref == 'refs/heads/main'
        uses: readmeio/rdme@7.5.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=1.0
